logging:
    file:
        name: logs/ch09.log
    level:
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8090
    servlet:
        context-path: /ch09
spring:
    application:
        name: ch09
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        password: 1234
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: thswlsdlf0000
    devtools:
        livereload:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

JWT:
    issuer: thswlsdlf0000@gmail.com
    secret: C13152E8251794C34FBF55F711234101111111111